name: Tests

on: 
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        working-directory: github-actions/day1/tests
        run: pytest